version: "2"
services:
  my_page_counter_app:
    image: snojo/week1:day2
    ports:
     - "80:3000"
    links:
     - my_postgres_container
  my_postgres_container:
    restart: always
    image: postgres
    environment: 
      POSTGRES_DB: hgop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
