version: "2"
services:
  my_page_counter_app:
    image: snojo/week1:day2
    ports:
     - "80:3000"
    links:
     - my_postgres_container
     - my_redis_container
  my_redis_container:
    image: redis
  my_postgres_container:
    restart: always
    image: postgres
    environment: 
      - POSTGRES_DB: HGOP
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: admin
