version: "2"
services:
  my_page_counter_app:
    image: snojo/week1:${COMMIT_ID}
    ports:
     - "80:3000"
    links:
     - my_postgres_container
     - my_redis_container
  my_redis_container:
    image: redis
  my_postgres_container:
    restart: always
    image: postgres
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hgop
